version: '3.8'

services:
  # Наш бот
  bot:
    build: .
    container_name: vpn_bot_app
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "alembic upgrade head && python main.py"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER:-postgres}:${DB_PASS:-postgres}@db:5432/${DB_NAME:-vpn_bot_db}
      - REDIS_URL=redis://redis:6379/0

  # Наша база данных PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: vpn_bot_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-vpn_bot_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-vpn_bot_db}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # Наш кэш и хранилище Redis
  redis:
    image: redis:7.2-alpine
    container_name: vpn_bot_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: vpn_bot_network
