"""add_trial_used_to_user

Revision ID: 034d80e2fb54
Revises: 90696c62247d
Create Date: 2026-03-31 00:31:27.282969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034d80e2fb54'
down_revision: Union[str, Sequence[str], None] = '90696c62247d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_used', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_used')
    # ### end Alembic commands ###
