"""Add referred_by field

Revision ID: 3d988840f2ae
Revises: 4adc09c09173
Create Date: 2026-03-30 23:41:49.718785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d988840f2ae'
down_revision: Union[str, Sequence[str], None] = '4adc09c09173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_by', sa.BigInteger(), nullable=True))
    op.drop_column('users', 'vless_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vless_link', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('users', 'referred_by')
    # ### end Alembic commands ###
