"""refactor_user_and_transaction_ids

Revision ID: 90696c62247d
Revises: 87f3a7374695
Create Date: 2026-03-31 00:19:38.855991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90696c62247d'
down_revision: Union[str, Sequence[str], None] = '87f3a7374695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=False)
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    # ### end Alembic commands ###
